# Generated by Django 3.2.6 on 2025-01-21 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('movies', '0002_movie_rating'),
        ('ratings', '0002_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='movie',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='reviewer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewers', to='accounts.reviewer'),
        ),
    ]
