# Generated by Django 3.2.6 on 2025-01-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20250127_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cast_images/'),
        ),
        migrations.AlterField(
            model_name='director',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='director_images/'),
        ),
    ]
