# Generated by Django 3.2.6 on 2025-01-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20250127_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizer',
            name='image',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cast',
            name='Nationality',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cast',
            name='image',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='image',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='image',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
