# Generated by Django 3.2.6 on 2025-01-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.FloatField(blank=True, default=0.0, max_length=5, null=True),
        ),
    ]
