# Generated by Django 3.2.6 on 2025-01-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(blank=True, default=None, max_length=5, null=True),
        ),
    ]
